# Generated by Django 4.2.6 on 2023-10-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodinventory',
            name='blood_bank',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='blood_bank',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.DeleteModel(
            name='BloodBank',
        ),
        migrations.DeleteModel(
            name='BloodInventory',
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
