# Generated by Django 4.2.6 on 2023-10-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blooddonationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
