# Generated by Django 4.2.6 on 2023-10-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_blooddonationrequest_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonationRequest',
        ),
    ]
