# Generated by Django 4.2.6 on 2023-10-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodbankName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('ContactNumber', models.CharField(max_length=13)),
                ('emailID', models.EmailField(max_length=100)),
            ],
        ),
    ]
