# Generated by Django 4.2.6 on 2023-10-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='bloodankUsername',
            new_name='bloodbankUsername',
        ),
    ]
